@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ReadOnlyResidencyBook <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniquePersonList
Class Person
Class Address
Class Email
Class Name
Class Phone
Class Tag
Class Nric

Class RoomList
Class Room
Class RoomNumber
Class Vacancy
Class ResidencyBook
Class Residency

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> "*" Tag
Person *--> Nric

AddressBook *--> "1" RoomList
RoomList --> "~* all" Room
Room *--> RoomNumber
Room *--> Vacancy
Room *--> "*" Person
Room *--> "1..*" Tag


Name -[hidden]right-> Phone
Phone -[hidden]right-> Address
Address -[hidden]right-> Email

AddressBook *-left-> "2" ReadOnlyResidencyBook
ResidencyBook .up.|> ReadOnlyResidencyBook
ResidencyBook --> "~*" Residency
ResidencyBook --> "~*" Room
ResidencyBook --> "~*" Person
Residency --> "1...*" Person
Residency --> "1" Room


ModelManager -->"~* filtered" Person
@enduml
